---
# handlers file for nifi

- name: reload systemctl
  command: systemctl daemon-reload

- name: restart kafka-manager
  service: name=kafka-manager state=restarted enabled=yes
  when: kafka_manager_perform_restart
